### PR TITLE
chore(fix): refactor image create/delete test

### LINKED ISSUE #8730: The build failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: f467a4e0847fc5a219f45ac58e282409f49d7301
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/70ff785a-2221-426d-94aa-46ac2c8e393e), [Sponge](http://sponge2/70ff785a-2221-426d-94aa-46ac2c8e393e)
status: failed
<details><summary>Test output</summary><br><pre>com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29.997756606s. [closed=[], open=[[buffered_nanos=10289231, remote_addr=monitoring.googleapis.com/74.125.197.95:443]]]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29.997756606s. [closed=[], open=[[buffered_nanos=10289231, remote_addr=monitoring.googleapis.com/74.125.197.95:443]]]
</pre></details>

### PR DESCRIPTION
**Pull request by minherz**
combine image creation and deletion into the one test. assert that image is created before deleting it.

### Description
Combines tests for create and delete image code samples in the single test.
Assert that the image is eventually created (READY) before deleting it.

Fixes #8730

### CODE REVIEW

File: compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java [hunk 1]
```diff
@@ -151,27 +147,27 @@ public void beforeEach() {
...
-  public void testCreateWindowsImage_failDueToRunningInstance()
+  public void testCanCreateImage()
       throws IOException, ExecutionException, InterruptedException, TimeoutException {
-    Assertions.assertThrows(
-        IllegalStateException.class,
-        () -> CreateImage.createImage(PROJECT_ID, ZONE, DISK_NAME, IMAGE_NAME,
-            "eu", false),
-        String.format("Instance %s should be stopped.", INSTANCE_NAME));
+    CreateImage.createImage(
+        PROJECT_ID, ZONE, getBootDiskName(testInstanceName), testImageName, "us", true);
```
Comment (kweinmeister) [inline compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java:157]: Should we make "us" a constant? Previously this was set to "eu" and it may be helpful to flag that more clearly in the sample.

**Review by kweinmeister — APPROVED** [review]

File: compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java [hunk 2]
```diff
@@ -55,94 +54,91 @@ public class WindowsOsImageIT {
...
-      throws IOException, ExecutionException, InterruptedException, TimeoutException {
-    final PrintStream out = System.out;
-    ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
-    System.setOut(new PrintStream(stdOut));
 
-    requireEnvVar("GOOGLE_APPLICATION_CREDENTIALS");
-    requireEnvVar("GOOGLE_CLOUD_PROJECT");
-
-    // Cleanup existing test instances.
-    Util.cleanUpExistingInstances("windowsimage-test-instance-", PROJECT_ID, ZONE);
```
Comment (Sita04) [inline compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java:84]: Should this line be retained? It will ensure that instances from any previous failed runs are cleaned up.

File: compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java (hunk 1 above)
Comment (minherz) [reply compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java:157]: It is set to `"us"` only to speed up the process because our tests run in the `us-central1` region. Since it is used only once I think that converting it to a constant can be postponed.

File: compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java (hunk 2 above)
Comment (minherz) [reply compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java:84]: This line is removed following the best practice of "fail sooner". The tests should clean up the environment. If they don't we want means to discover it. This clean up line, ran in the test `setup()` does not let us to do it.
