### PR TITLE
fix(monitoring): refactor a few monitoring ITs

### LINKED ISSUE #7912: com.example.monitoring.AlertIT: testListPolicies failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: e4617d94abba431578bb81ff637e928538cc6fe5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b317f232-61cc-4a3a-9fda-1bd9f83423c1), [Sponge](http://sponge2/b317f232-61cc-4a3a-9fda-1bd9f83423c1)
status: failed
<details><summary>Test output</summary><br><pre>java.lang.AssertionError
	at com.example.monitoring.AlertIT.testListPolicies(AlertIT.java:69)
</pre></details>

### LINKED ISSUE #7913: com.example.monitoring.ListAlertPolicyIT: listAlertPolicyTest failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: e4617d94abba431578bb81ff637e928538cc6fe5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b317f232-61cc-4a3a-9fda-1bd9f83423c1), [Sponge](http://sponge2/b317f232-61cc-4a3a-9fda-1bd9f83423c1)
status: failed
<details><summary>Test output</summary><br><pre>com.google.common.truth.AssertionErrorWithFacts: 
expected to contain: success! alert policy
but was            : 
	at com.example.monitoring.ListAlertPolicyIT.listAlertPolicyTest(ListAlertPolicyIT.java:71)
</pre></details>

### LINKED ISSUE #7914: com.example.monitoring.AlertIT: testDisableEnablePolicies failed
Note: #7572 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: e4617d94abba431578bb81ff637e928538cc6fe5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b317f232-61cc-4a3a-9fda-1bd9f83423c1), [Sponge](http://sponge2/b317f232-61cc-4a3a-9fda-1bd9f83423c1)
status: failed
<details><summary>Test output</summary><br><pre>java.lang.AssertionError
	at com.example.monitoring.AlertIT.testDisableEnablePolicies(AlertIT.java:121)
</pre></details>

### LINKED ISSUE #7915: com.example.monitoring.AlertIT: testBackupPolicies failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: e4617d94abba431578bb81ff637e928538cc6fe5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b317f232-61cc-4a3a-9fda-1bd9f83423c1), [Sponge](http://sponge2/b317f232-61cc-4a3a-9fda-1bd9f83423c1)
status: failed
<details><summary>Test output</summary><br><pre>java.lang.AssertionError
	at com.example.monitoring.AlertIT.testBackupPolicies(AlertIT.java:78)
</pre></details>

### LINKED ISSUE #7916: com.example.monitoring.AlertIT: testReplaceChannels failed
Note: #7574 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: e4617d94abba431578bb81ff637e928538cc6fe5
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b317f232-61cc-4a3a-9fda-1bd9f83423c1), [Sponge](http://sponge2/b317f232-61cc-4a3a-9fda-1bd9f83423c1)
status: failed
<details><summary>Test output</summary><br><pre>java.lang.AssertionError
	at com.example.monitoring.AlertIT.testReplaceChannels(AlertIT.java:91)
</pre></details>

### PR DESCRIPTION
**Pull request by anguillanneuf**
fixes #7916
fixes #7915
fixes #7914
fixes #7913
fixes #7912

i see other badly written tests in this /monitoring directory that will need a larger scale rewrite
- inconsistent use of resource id versus resource names
- not all samples have tests
- unnecessary ITs for each sample, with this type of admin ops, ITs can be combined into a single IT
- repeated use of functions like `requireEnvVar` in each IT and can be extracted instead
- the `java-pubsub` samples repo have some really good examples that can be ref'ed

for now, i've done a few things while being aware that there's a 500 hard limit on alerting policies per google cloud project. these include:
- create test resources for each IT run (of the ITs i touched) and clean them up 
- use consistent naming for resource ids versus names
- rewrite create resource sample to return resource type, where we can extract resource names, rather than using a list method

### CODE REVIEW

File: monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ public void tearDown() {
   @Test
   public void testListPolicies() throws IOException {
     AlertSample.main(new String[] {"list"});
-    assertTrue(bout.toString().contains(testPolicyName));
+    assertTrue(bout.toString().contains("My Uptime Check Policy"));
```
Comment (kweinmeister) [inline monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java:69]: Thanks for this fix @anguillanneuf! Should we consider referencing the updated variable `testPolicyName` in each test, rather than repeating the raw string?

Comment (anguillanneuf) [reply monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java]: ohh, this wasn't the root of the problem as i later found out.

**Review by averikitsch — APPROVED** [review]
