### PR TITLE
fix: broken tests due to API changes; enable tests again

### LINKED ISSUE #7845: Update media/stitcher samples
The stitcher API has breaking changes and the [media/stitcher](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/media/stitcher) samples need to be updated, see [issues](https://github.com/GoogleCloudPlatform/java-docs-samples/issues?q=is%3Aissue+stitcher).

### PR DESCRIPTION
**Pull request by irataxy**
## Description

Fixes #7845

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [X] Please **merge** this PR for me once it is approved

### CODE REVIEW

File: media/stitcher/src/main/java/com/example/stitcher/CreateLiveConfig.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                  .setSourceUri(sourceUri)
+                  .setAdTagUri(adTagUri)
+                  .setDefaultSlate(SlateName.format(projectId, location, slateId))
+                  .setAdTracking(AdTracking.SERVER)
+                  .setStitchingPolicy(StitchingPolicy.CUT_CURRENT).build())
+              .build();
+
+      LiveConfig response = videoStitcherServiceClient.createLiveConfigAsync(
+              createLiveConfigRequest)
+          .get(2, TimeUnit.MINUTES);
```
Comment (kweinmeister) [inline media/stitcher/src/main/java/com/example/stitcher/CreateLiveConfig.java:73]: 2 minutes is used throughout the samples. Any thoughts on making that a constant in each file or `TestUtils`?

Comment (irataxy) [reply media/stitcher/src/main/java/com/example/stitcher/CreateLiveConfig.java]: Made this a constant in each sample file

**Review by kweinmeister — APPROVED** [review]
