### PR TITLE
Fixes some lint errors.

### LINKED ISSUE #2645: Fix IoT lint errors
## In which file did you encounter the issue?
iot/api-client/manager

### Did you change the file? If so, how?
No files changed.

## Describe the issue
Build is throwing new lint errors.

### PR DESCRIPTION
**Pull request by gguuss**
Fixes #2645

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)

### CODE REVIEW

**Comment by gguuss** [comment]
@lesv It appears that we added new lint rules that are blocking these changes at presubmit.

**Comment by nnegrey** [comment]
Yea, it shouldn't block on these.

**Comment by lesv** [comment]
1.0.15 doesn't block

**Comment by lesv** [comment]
You might not have a current pom

**Comment by lesv** [comment]
# Java 8
The only thing blocking you is the compilation errors at the end, the other stuff can be ignored.
```
------------------------------------------------------------
- testing iot/api-client/manager
------------------------------------------------------------
     [java] JVM args ignored when same JVM is used.
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.bindDeviceToGateway(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 927-956] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.createDevice(String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 997-1051] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.createDeviceWithEs256(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 332-367] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.createDeviceWithNoAuth(String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 428-453] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.createDeviceWithRs256(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 380-414] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.createGateway(String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 1064-1110] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.deleteDevice(String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 462-477] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.getDevice(String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 486-500] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.getDeviceStates(String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 510-528] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.getIamPermissions(String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 779-812] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.getRegistry(String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 538-550] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.patchEs256ForAuth(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 643-678] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.patchRsa256ForAuth(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 691-726] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.sendCommand(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 890-920] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.setDeviceConfiguration(String, String, String, String, String, long) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 740-771] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.setIamPermissions(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 821-881] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.unbindDeviceFromGateway(String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[lines 963-989] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This API (java/io/File.<init>(Ljava/lang/String;)V) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 345]At DeviceRegistryExample.java:[line 1202] PATH_TRAVERSAL_IN
[ERROR] This API (java/io/File.<init>(Ljava/lang/String;)V) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 393]At DeviceRegistryExample.java:[line 1207] PATH_TRAVERSAL_IN
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 1091]At DeviceRegistryExample.java:[line 1224]At DeviceRegistryExample.java:[line 1227]At DeviceRegistryExample.java:[line 1230] PATH_TRAVERSAL_IN
[ERROR] This API (java/io/File.<init>(Ljava/lang/String;)V) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 657]At DeviceRegistryExample.java:[line 1295] PATH_TRAVERSAL_IN
[ERROR] This API (java/io/File.<init>(Ljava/lang/String;)V) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.DeviceRegistryExample, com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 705]At DeviceRegistryExample.java:[line 1303] PATH_TRAVERSAL_IN
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.main(String[]) parses a String that is a field [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 1269] STT_STRING_PARSING_A_FIELD
[ERROR] This method com.example.cloud.iot.examples.DeviceRegistryExample.main(String[]) parses a String that is a field [com.example.cloud.iot.examples.DeviceRegistryExample] At DeviceRegistryExample.java:[line 1273] STT_STRING_PARSING_A_FIELD
[ERROR] Class com.example.cloud.iot.examples.DeviceRegistryExampleOptions does not implement an equals method [com.example.cloud.iot.examples.DeviceRegistryExampleOptions] At DeviceRegistryExampleOptions.java:[lines 31-269] IMC_IMMATURE_CLASS_NO_EQUALS
[ERROR] Method com.example.cloud.iot.examples.HttpExample.publishMessage(String, String, String, String, String, String, String, String) declares RuntimeException in throws clause [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[lines 161-217] DRE_DECLARED_RUNTIME_EXCEPTION
[ERROR] Result of integer multiplication cast to long in com.example.cloud.iot.examples.HttpExample.main(String[]) [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 258] ICAST_INTEGER_MULTIPLY_CAST_TO_LONG
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 262] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 264] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 272] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.HttpExample.publishMessage(String, String, String, String, String, String, String, String) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 165] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.HttpExample.publishMessage(String, String, String, String, String, String, String, String) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 190] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 274] MDM_THREAD_YIELD
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 277] MDM_THREAD_YIELD
[ERROR] This method com.example.cloud.iot.examples.HttpExample.getConfig(String, String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[lines 116-152] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.HttpExample.publishMessage(String, String, String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[lines 161-217] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.HttpExample, com.example.cloud.iot.examples.HttpExample, com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 102]At HttpExample.java:[line 236]At HttpExample.java:[line 265] PATH_TRAVERSAL_IN
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.HttpExample, com.example.cloud.iot.examples.HttpExample, com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 83]At HttpExample.java:[line 234]At HttpExample.java:[line 263] PATH_TRAVERSAL_IN
[ERROR] Method com.example.cloud.iot.examples.HttpExample.main(String[]) allocates an object that is used in a constant way in a loop [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 257] PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP
[ERROR] Class com.example.cloud.iot.examples.HttpExampleOptions does not implement a toString method [com.example.cloud.iot.examples.HttpExampleOptions] At HttpExampleOptions.java:[lines 30-167] IMC_IMMATURE_CLASS_NO_TOSTRING
[ERROR] HttpExampleOptions.algorithm not initialized in constructor and dereferenced in com.example.cloud.iot.examples.HttpExample.main(String[]) [com.example.cloud.iot.examples.HttpExample] At HttpExample.java:[line 262] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR
[ERROR] Format string argument allowing user controlled parameters [com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 164]At MqttExample.java:[line 136]At MqttExample.java:[line 247]At MqttExample.java:[line 276]At MqttExample.java:[line 516]At MqttExample.java:[line 528] FORMAT_STRING_MANIPULATION
[ERROR] Result of integer multiplication cast to long in com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 419] ICAST_INTEGER_MULTIPLY_CAST_TO_LONG
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 349] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 352] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 402] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 422] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 425] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 444] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.sendDataFromDevice(MqttClient, String, String, String) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 218] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.startMqtt(String, int, String, String, String, String, String, String) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 155] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.startMqtt(String, int, String, String, String, String, String, String) makes literal string comparisons passing the literal as an argument [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 157] LSC_LITERAL_STRING_COMPARISON
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 387] MDM_THREAD_YIELD
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 446] MDM_THREAD_YIELD
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 449] MDM_THREAD_YIELD
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 456] MDM_THREAD_YIELD
[ERROR] Method com.example.cloud.iot.examples.MqttExample.startMqtt(String, int, String, String, String, String, String, String) attempts to manually schedule threads by calling method Thread.sleep(long) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 191] MDM_THREAD_YIELD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.attachCallback(MqttClient, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 472-501] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.attachDeviceToGateway(MqttClient, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 295-302] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.detachDeviceFromGateway(MqttClient, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 308-315] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.listenForConfigMessages(String, short, String, String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 275-290] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 323-468] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.sendDataFromBoundDevice(String, short, String, String, String, String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 246-260] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.sendDataFromDevice(MqttClient, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 218-228] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This method com.example.cloud.iot.examples.MqttExample.startMqtt(String, int, String, String, String, String, String, String) is declared more permissively than is used in the code base [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[lines 130-211] OPM_OVERLY_PERMISSIVE_METHOD
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 106]At MqttExample.java:[line 158]At MqttExample.java:[line 247]At MqttExample.java:[line 276]At MqttExample.java:[line 353]At MqttExample.java:[line 354]At MqttExample.java:[line 426]At MqttExample.java:[line 427]At MqttExample.java:[line 516]At MqttExample.java:[line 528] PATH_TRAVERSAL_IN
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample, com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 85]At MqttExample.java:[line 156]At MqttExample.java:[line 247]At MqttExample.java:[line 276]At MqttExample.java:[line 350]At MqttExample.java:[line 351]At MqttExample.java:[line 423]At MqttExample.java:[line 424]At MqttExample.java:[line 516]At MqttExample.java:[line 528] PATH_TRAVERSAL_IN
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) allocates an object that is used in a constant way in a loop [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 418] PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) orders expressions in a conditional in a sub optimal way [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 375] SEO_SUBOPTIMAL_EXPRESSION_ORDER
[ERROR] Method com.example.cloud.iot.examples.MqttExample.startMqtt(String, int, String, String, String, String, String, String) orders expressions in a conditional in a sub optimal way [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 179] SEO_SUBOPTIMAL_EXPRESSION_ORDER
[ERROR] Method com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) passes constant String of length 1 to character overridden method [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 455] UCPM_USE_CHARACTER_PARAMETERIZED_METHOD
[ERROR] Class com.example.cloud.iot.examples.MqttExampleOptions does not implement a toString method [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[lines 29-214] IMC_IMMATURE_CLASS_NO_TOSTRING
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 60] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 76] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 91] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 111] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 126] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 140] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) appears to call the same method on the same object redundantly [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[line 154] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Method com.example.cloud.iot.examples.MqttExampleOptions.fromFlags(String[]) defines parameter list with array as last argument, rather than vararg [com.example.cloud.iot.examples.MqttExampleOptions] At MqttExampleOptions.java:[lines 49-214] UVA_USE_VAR_ARGS
[ERROR] MqttExampleOptions.algorithm not initialized in constructor and dereferenced in com.example.cloud.iot.examples.MqttExample.mqttDeviceDemo(MqttExampleOptions) [com.example.cloud.iot.examples.MqttExample] At MqttExample.java:[line 349] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR
[ERROR] Class com.example.cloud.iot.examples.RetryHttpInitializerWrapper does not implement a toString method [com.example.cloud.iot.examples.RetryHttpInitializerWrapper] At RetryHttpInitializerWrapper.java:[lines 36-102] IMC_IMMATURE_CLASS_NO_TOSTRING
[ERROR] This use of java/util/logging/Logger.info(Ljava/lang/String;)V might be used to include CRLF characters into log messages [com.example.cloud.iot.examples.RetryHttpInitializerWrapper$1, com.example.cloud.iot.examples.RetryHttpInitializerWrapper$1] At RetryHttpInitializerWrapper.java:[line 93]At RetryHttpInitializerWrapper.java:[line 93] CRLF_INJECTION_LOGS
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[73,10] error: no suitable constructor found for PrintStream(ByteArrayOutputStream,Charset)
    constructor PrintStream.PrintStream(boolean,OutputStream) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(OutputStream,boolean) is not applicable
      (argument mismatch; Charset cannot be converted to boolean)
    constructor PrintStream.PrintStream(String,String) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to String)
    constructor PrintStream.PrintStream(File,String) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to File)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[133,34] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[157,34] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[177,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[196,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[215,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[234,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[255,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,45] error: cannot find symbol
  symbol:   variable Charsets
  location: class ManagerIT
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[291,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[306,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[322,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[356,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[391,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[426,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[463,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[515,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[552,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[589,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[638,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[689,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[739,32] error: cannot find symbol
  symbol:   method getBytes()
  location: variable bout of type ByteArrayOutputStream
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project cloudiot-manager-demo: Compilation failure: Compilation failure:
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[73,10] error: no suitable constructor found for PrintStream(ByteArrayOutputStream,Charset)
[ERROR]     constructor PrintStream.PrintStream(boolean,OutputStream) is not applicable
[ERROR]       (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
[ERROR]     constructor PrintStream.PrintStream(OutputStream,boolean) is not applicable
[ERROR]       (argument mismatch; Charset cannot be converted to boolean)
[ERROR]     constructor PrintStream.PrintStream(String,String) is not applicable
[ERROR]       (argument mismatch; ByteArrayOutputStream cannot be converted to String)
[ERROR]     constructor PrintStream.PrintStream(File,String) is not applicable
[ERROR]       (argument mismatch; ByteArrayOutputStream cannot be converted to File)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[133,34] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[157,34] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[177,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[196,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[215,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[234,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[255,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,45] error: cannot find symbol
[ERROR]   symbol:   variable Charsets
[ERROR]   location: class ManagerIT
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[291,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[306,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[322,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[356,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[391,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[426,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[463,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[515,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[552,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[589,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[638,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[689,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[739,32] error: cannot find symbol
[ERROR]   symbol:   method getBytes()
[ERROR]   location: variable bout of type ByteArrayOutputStream
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by lesv** [comment]
Note - you might wish to edit the pom.xml and make sure your on the latest version of the client library.

**Comment by gguuss** [comment]
My libraries and inherited rules are up-to-date. Investigating futher.

**Comment by gguuss** [comment]
I've put in around 20 hours so far trying to resolve these new lint errors and I still have 153 fresh issues that are making it difficult to assess. 

Specific to the red ones around usage of `ByteArrayOutputStream` If you have suggestions for the fixes, happy to hear them, I have tried:

```
bout.toString(StandardCharsets.UTF_8)
```

```
new String(bout.getByteArray(), StandardCharsets.UTF_8)
```

```
new PrintStream(bout.getByteArray(), true, StandardCharsets.UTF_8)
```

and other iterations of these.

**Comment by gguuss** [comment]
After making some changes it appears that the spotbugs plugin was caching my builds, might have a solution pushed.

**Comment by gguuss** [comment]
Still working on it, but it appears that `mvn clean` is essential when diagnosing `mvn:spotbugs`.

**Comment by lesv** [comment]
# Java 8
The only blocking issues are:
```
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[75,18] error: no suitable constructor found for PrintStream(ByteArrayOutputStream,boolean,Charset)
    constructor PrintStream.PrintStream(boolean,OutputStream,Charset) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(boolean,Charset,OutputStream) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(OutputStream,boolean,String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[133,23] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[157,23] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[177,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[196,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[215,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[234,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[255,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[291,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[306,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[322,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[356,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[391,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[426,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[463,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[515,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[552,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[589,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[638,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[689,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)

```

**Comment by lesv** [comment]
Ping when you are around, we should talk.

**Comment by gguuss** [comment]
@lesv I'll reach out to you later today :)

**Comment by lesv** [comment]
# Java 8
These aren't spotbugs issues, they are a lack of conversion.
```
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[75,18] error: no suitable constructor found for PrintStream(ByteArrayOutputStream,boolean,Charset)
    constructor PrintStream.PrintStream(boolean,OutputStream,Charset) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(boolean,Charset,OutputStream) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(OutputStream,boolean,String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[133,23] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[157,23] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[177,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[196,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[215,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[234,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[255,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[274,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[291,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[306,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[322,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[356,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[391,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[426,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[463,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[515,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[552,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[589,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[638,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[689,21] error: no suitable method found for toString(Charset)
    method ByteArrayOutputStream.toString(String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
    method ByteArrayOutputStream.toString(int) is not applicable
      (argument mismatch; Charset cannot be converted to int)
```

File: iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java [hunk 1]
```diff
@@ -68,8 +72,7 @@ public void setUp() throws Exception {
     }
 
     bout = new ByteArrayOutputStream();
-    out = new PrintStream(bout);
-    System.setOut(out);
+    System.setOut(new PrintStream(bout, true, StandardCharsets.UTF_8));
```
Comment (lesv) [inline iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:75]:
```
[ERROR] /tmpfs/src/github/java-docs-samples/iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java:[75,18] error: no suitable constructor found for PrintStream(ByteArrayOutputStream,boolean,Charset)
    constructor PrintStream.PrintStream(boolean,OutputStream,Charset) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(boolean,Charset,OutputStream) is not applicable
      (argument mismatch; ByteArrayOutputStream cannot be converted to boolean)
    constructor PrintStream.PrintStream(OutputStream,boolean,String) is not applicable
      (argument mismatch; Charset cannot be converted to String)
```
Try setting `StandardCharsets.UTF_8.name()` instead.

**Comment by lesv** [comment]
Force pushed - Gus tells me it works, this crashed SpotBugs or one of the other plugins.  I'll be looking into that.
