### PR TITLE
fix: delete container image after test

### LINKED ISSUE #8358: Clean up Run/Filesystem images
The run filesystem sample needs to be updated to clean up AR images in https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java

### PR DESCRIPTION
**Pull request by averikitsch**
## Description

Fixes #8358

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

File: run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java [hunk 1]
```diff
@@ -131,8 +131,25 @@ public static void cleanup() throws IOException, InterruptedException {
         "--project=" + project);
 
     System.out.println("Deleting Cloud Run service: " + service);
-    Process p = delete.start();
-    p.waitFor(5, TimeUnit.MINUTES);
+    Process p1 = deleteService.start();
+    p1.waitFor(5, TimeUnit.MINUTES);
```
Comment (kweinmeister) [inline run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java:135]: If p1 and p2 are independent processes, we could optimize the wait time by moving `p1.waitFor()` between when we start p2 and `p2.waitFor()`. That would enable the container deletion start before we block on p1.

**Review by kweinmeister — APPROVED** [review]
