### PR TITLE
small changes test and added sleep time between search func

### LINKED ISSUE #2261: SampleTests: customAttributeSampleTest failed
buildID: 9e0488246b98d859d260e845e9644c7e1b18c4f1
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/45bb983a-7630-46cf-b3f7-8365699020fc), [Sponge](http://sponge2/45bb983a-7630-46cf-b3f7-8365699020fc)
status: failed

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #2261 #2232

### CODE REVIEW

File: jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java [hunk 1]
```diff
@@ -31,27 +31,24 @@
 /**
  * The sample in this file introduce featured job, including:
  *
- * - Construct a featured job
+ * <p>- Construct a featured job
  *
- * - Search featured job
+ * <p>- Search featured job
```
Comment (lesv) [inline jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java:36]: Doc samples don't need `<p>`

File: jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java [hunk 2]
```diff
@@ -31,27 +31,24 @@
...
 
-  /**
-   * Creates a job as featured.
-   */
+  /** Creates a job as featured. */
   public static Job generateFeaturedJob(String companyName) throws IOException {
     // requisition id should be a unique Id in your system.
-    String requisitionId =
-        "featuredJob:" + String.valueOf(new Random().nextLong());
+    String requisitionId = "featuredJob:" + String.valueOf(new Random().nextLong());
```
Comment (lesv) [inline jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java:51]: Ok, but it's better to use a real UUID than a Random as that's not guaranteed to truly be random.

Comment (munkhuushmgl) [reply jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java:51]: I will make these changes
