### PR TITLE
Determine pubsub event timestamp correctly in retry-timeout.

### LINKED ISSUE #3734: Java retry timeout should use context.timestamp to test event age
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java

### Did you change the file? If so, how?
This is how I'm checking the event age.
```
@Override
  public void accept(PubSubMessage message, Context context) {
    ZonedDateTime utcNow = ZonedDateTime.now(ZoneOffset.UTC);
    ZonedDateTime timestamp = ZonedDateTime.parse(context.timestamp());
    long eventAge = Duration.between(timestamp, utcNow).toMillis();

    // Ignore events that are too old
    if (eventAge > MAX_EVENT_AGE) {
      logger.info(String.format("Dropping event %s.", context.eventId()));
      return;
    }

    // Process events that are recent enough
    // To retry this invocation, throw an exception here
    logger.info(String.format("Processing event %s.", context.eventId()));
  }
```

## Describe the issue
Using Java, I've recently tried to implement a background [Cloud Function retry timeout](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java) to avoid infinite retries. I've implemented the same check in Go and Javascript in the past. I noticed that the Java sample differs from the Go and Javascript samples. Go and Javascript both base the event duration on the `timestamp` property of the `context` object. I believe this is the correct way to determine the age of the event pubsub. The Java sample attempts to determine the event age using `message.getData()` which holds user defined data. There is no timestamp in the message data unless the users adds it.

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
In the retry-timeout sample for GCF java11, we should determine
the event timestamp from the Context parameter, not from properties
of the passed-in PubSub object.

Fixes #3734.

### CODE REVIEW

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java [hunk 1]
```diff
@@ -42,25 +41,19 @@
   @Override
   public void accept(PubSubMessage message, Context context) {
     ZonedDateTime utcNow = ZonedDateTime.now(ZoneOffset.UTC);
-    ZonedDateTime timestamp = utcNow;
+    ZonedDateTime timestamp = ZonedDateTime.parse(context.timestamp());
```
Comment (lesv) [inline functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: Shouldn't there be some kind of comment discussing these two and why they are different and when you want to use one and not the other?

**Review by lesv — CHANGES_REQUESTED** [review]
Great - shouldn't we explain it to the user?

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java (hunk 1 above)
Comment (ace-n) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: @lesv I suspect @eamonnmcmanus meant to delete the `utcNow` declaration?

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java [hunk 2]
```diff
@@ -42,25 +41,19 @@
   @Override
   public void accept(PubSubMessage message, Context context) {
     ZonedDateTime utcNow = ZonedDateTime.now(ZoneOffset.UTC);
```
Comment (ace-n) [inline functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:43]: @eamonnmcmanus did you mean to delete this?

File: functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java [hunk 3]
```diff
@@ -65,41 +64,29 @@ public void afterTest() {
...
-    new RetryTimeout().accept(pubsubMessage, null);
+    new RetryTimeout().accept(pubsubMessage, mockContext);
 
     String logMessage = LOG_HANDLER.getStoredLogRecords().get(0).getMessage();
-    assertThat(String.format("Processing event %s.", timestampData)).isEqualTo(logMessage);
+    assertThat(logMessage).contains("Processing event with timestamp " + timestamp);
   }
 
   @Test
   public void retryTimeout_handlesStopMsg() {
```
Comment (ace-n) [inline functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java:80]: Should this test contain an assertion? (I don't think it does right now.)

**Review by ace-n — CHANGES_REQUESTED** [review]

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java (hunk 1 above)
Comment (lesv) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: Still, there are two sources of truth, and we got it wrong the first time, so that deserves an explanation, since other users are likely to make the same error unless they are told why.

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java (hunk 2 above)
Comment (ace-n) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:43]: Edit: nvm, I see you used it below.

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java (hunk 1 above)
Comment (ace-n) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: Ah - I misread, he's comparing `utcNow` to the parsed timestamp. (`utcNow` was previously the _default timestamp value_ in case one wasn't included in the Pub/Sub message.)

This LGTM. ✅

Comment (eamonnmcmanus) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: I think the situation is pretty confusing here. I don't know under what circumstances, if any, the `messageId` and `publishTime` properties of the payload are set. I just deployed a pub/sub function and sent a message to it, and both these fields were null. We may have a much bigger cleanup to do to get this straight, though hopefully the migration to CloudEvents should make things more consistent.

Anyway, let's get this fix in for now, and try to improve things further afterwards.

File: functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java (hunk 3 above)
Comment (eamonnmcmanus) [reply functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java:80]: If you're looking at the diffs it can be confusing, since I deleted the empty-payload test. The two remaining test methods are basically identical apart from the timestamp, and the assertion is on the last line of each.

File: functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java (hunk 1 above)
Comment (lesv) [reply functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java:44]: k - I'd still rather you commented about it in the source, but it's up to you.

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
I'm going to dismiss @ace-n review based on @eamonnmcmanus comments.  I'd like to see comments, hopefully that will get fixed in the next PR.
