### PR TITLE
fix: talent solution v4 samples tests

### LINKED ISSUE #2970: HistogramSearchJobsTest: testHistogramSearch failed
Note: #2683 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 0870bb87302faf041ec1f252b530ebc07c31d8af
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/4508cdab-9110-4aab-9465-6ea314b6b4a8), [Sponge](http://sponge2/4508cdab-9110-4aab-9465-6ea314b6b4a8)
status: failed
<details><summary>Test output</summary><br><pre>expected to contain: Job summary:
but was            : 
	at HistogramSearchJobsTest.testHistogramSearch(HistogramSearchJobsTest.java:47)
</pre></details>

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #2970

Looks like job posting by default was expired and deleted in 30 days.
That's why this happens once in a month.

I found out that I can customize the expiration date in job posting, and created one job for testing that expires in 40 years from now.

### CODE REVIEW

File: jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java [hunk 1]
```diff
@@ -22,6 +22,8 @@
 import com.google.cloud.talent.v4beta1.Job;
 import com.google.cloud.talent.v4beta1.JobServiceClient;
 import com.google.cloud.talent.v4beta1.TenantName;
+import com.google.protobuf.Timestamp;
+import com.google.protobuf.util.Timestamps;
```
Comment (lesv) [inline jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:26]: This wouldn't be my first choice.  https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html would be better.

File: jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java [hunk 2]
```diff
@@ -46,14 +48,27 @@ public static void createJob(
...
+              "1600 Amphitheatre Parkway, Mountain View, CA 94043",
               "111 8th Avenue, New York, NY 10011");
 
+      // if exp date is not set, by default it will expire in 30 days.
+      Timestamp expirationDate =
+          Timestamps.add(
+              Timestamps.fromMillis(System.currentTimeMillis()),
+              com.google.protobuf.Duration.newBuilder()
+                  .setSeconds(60L * 60L * 24L * 30L) //  30 days ago
+                  .build());
```
Comment (lesv) [inline jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:70]: https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html <== Is protobuf timestamp leaked to users?  Is this really a good idea?

File: jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java (hunk 1 above)
Comment (munkhuushmgl) [reply jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:26]: Okay I will change it to sql Timestamp

File: jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java (hunk 2 above)
Comment (lesv) [reply jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:70]: I may have copied the wrong one.  I think LocalDate https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html is the Java 8 hotness. (if it works)

Comment (lesv) [reply jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:70]: And LocalDateTime https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html

Comment (munkhuushmgl) [reply jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java:70]: I referenced from appengine Java 8 
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/caebd85cdda8e3647e33f9f83c64ea3b1b0a0673/appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/BigQueryRunner.java#L199

File: jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java (hunk 1 above)
Comment (munkhuushmgl) [reply jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java]: Looks like method that sets expiration date specifically takes this Timestamp:
```
setPostingExpireTime(com.google.protobuf.Timestamp)
```

Since it is discouraged, I will take this out and just comment it about 30 days expiration. Also, it is also mentioned in the docs, https://cloud.google.com/talent-solution/job-search/docs/jobs

**Comment by munkhuushmgl** [comment]
@lesv Looks like I do not have a write permission to merge this
